### ISSUE TITLE
As a Visitor/User, I should be able to add and edit my cart, so that I can control what I'm buying.

### ISSUE THREAD

**Issue by houpos** [honey-nut-cheerinodes/grace-shopper#11]
Implementation: An Express route on the backend
(GET `/api/cart`) should serve up the name, quantity, user id, and product id of the cart from our Postgres database. No special access control is needed, since any visitor should be able to receive this information. A React component should serve up the cart view via reducers, store, CSS, et al. It should include buttons to add and remove products and update the subtotal.

Backend:
- [x] `orders` route
- [x] `orders` model
- [x] `orderItems` model
- [x] Associations
- [x] Dummy data in seed.js

Frontend:
- [x] `cart` component
- [x] `cart-products` component
- [x] `cart-items` component
- [x] `order-summary` component
- [x] Reducer
- [x] Action types and creators (four buttons and `get`)
- [x] Thunk creators/thunks (four buttons and `get`)
- [x] CSS for `cart`, `cart-items`, and `order-summary` components

**Comment by windyseng** [comment]
Updated completed items.  Still needs remove button on checkout.
