### ISSUE TITLE
As a Visitor, I should be able to see all information on a product, so that I know what I'm buying.

### ISSUE THREAD

**Issue by houpos** [honey-nut-cheerinodes/grace-shopper#5]
Implementation: An Express route on the backend
(GET `/api/products/:id`) should serve up the name, price, and imageUrl of the product selected by id from our Postgres database. No special access control is needed, since any visitor should be able to receive this information. A React component should serve up a single-product view via reducers, store, CSS, et al.

Single Product:
- [x] Route
- [x] Model
- [x] Component
- [x] Reducers
- [x] Store
- [x] CSS

**Comment by windyseng** [comment]
All Single Product Components completed except for "Add to Bag" functionality that requires sessions.
